### PR TITLE
fix: gracefully handle merge failures

### LINKED ISSUE #471: Error on running action
**How would you describe the issue?**

From little time ago I get the following error:
```
Automatic merges enabled for GitHub login: dependabot-preview[bot].
Found pull request information: {"reviewEdges":[]}.
##[warning]MERGE_METHOD value input is ignored because its malformed, defaulting to SQUASH.
##[error]GraphqlError: 2 of 2 required status checks have not succeeded: 1 expected.
```

I suspect this dependency update: 
https://github.com/ridedott/merge-me-action/commit/d9046acb40d33a7dc5ae33423b403bac58a5264b

**How can we reproduce the issue?**

Used workflow:
https://github.com/camptocamp/ngeo/blob/master/.github/workflows/dependabot-auto-merge.yaml

**What are the expected results?**

Validate the PR

**What are the actual results?**

Error in workflow

**How much does it hurt?**

The action doesn't work anymore...

### PR DESCRIPTION
**Pull request by merlinnot**
This Pull Request fulfills the following requirements:

- [x] The commit message follows our guidelines.
- [x] Tests for the changes have been added if needed.
- [x] Does not affect documentation or it has been added or updated.

Resolves #471

### CODE REVIEW

File: src/eventHandlers/checkSuite/index.ts [hunk 1]
```diff
@@ -172,7 +182,7 @@ export const checkSuiteHandle = async (
         await tryMerge(octokit, pullRequestInformation);
       }
     } catch (error) {
-      setFailed(error);
+      logInfo(`An error ocurred when merging the branch. This is usually an `);
```
Comment (oleg-koval) [inline src/eventHandlers/checkSuite/index.ts]: looks like some text here is missing

Comment (merlinnot) [reply src/eventHandlers/checkSuite/index.ts]: Fixed!
